import { Persona } from './types';

export const PERSONAS: Persona[] = [
  {
    id: 'persona-maya',
    name: 'Maya',
    avatar: require('@/assets/images/personas/maya-chen.png'),
    accentColor: '#e8b4a2',
    age: 25,
    subtitle: 'New member, no history with Coach',
    flows: [
      { scenarioId: '', label: 'Free chat', icon: 'message-circle', description: 'Open conversation with Coach' },
      { scenarioId: 'cold-start', label: 'First-time onboarding', icon: 'sparkles', description: 'New member meets Coach for the first time' },
    ],
    financialProfile: {
      greeting: 'Good morning, Maya',
      bankingBalance: '$3,847.52',
      bankingCount: 1,
      creditCardBalance: '$4,200',
      monthlyIncome: '$9,580',
      creditScore: 698,
      creditScoreLabel: 'Fair',
      netWorth: '$1,748',
      spending: '$4,680',
      spendingNote: 'On track this month',
      rewardPoints: '120 pts',
    },
  },
  {
    id: 'persona-marcus',
    name: 'Marcus',
    avatar: require('@/assets/images/personas/marcus-johnson.png'),
    accentColor: '#e5d38a',
    age: 32,
    subtitle: 'Active goals, regular check-ins',
    flows: [
      { scenarioId: '', label: 'Free chat', icon: 'message-circle', description: 'Open conversation with Coach' },
      { scenarioId: 'returning-member', label: 'Personalized check-in', icon: 'user-check', description: 'Coach remembers past context and goals' },
    ],
    financialProfile: {
      greeting: 'Good morning, Marcus',
      bankingBalance: '$12,450.00',
      bankingCount: 2,
      investBalance: '$38,200',
      creditCardBalance: '$2,940',
      monthlyIncome: '$12,083',
      creditScore: 742,
      creditScoreLabel: 'Good',
      netWorth: '$89,400',
      spending: '$892',
      spendingNote: '↓8% from last week',
      rewardPoints: '250 pts',
    },
  },
  {
    id: 'persona-jordan',
    name: 'Jordan',
    avatar: require('@/assets/images/personas/jordan-rivera.png'),
    accentColor: '#b5c4a0',
    age: 28,
    subtitle: 'Carries debt, needs a payoff plan',
    flows: [
      { scenarioId: '', label: 'Free chat', icon: 'message-circle', description: 'Open conversation with Coach' },
      { scenarioId: 'cold-start', label: 'First-time onboarding', icon: 'sparkles', description: 'New member meets Coach for the first time' },
    ],
    financialProfile: {
      greeting: 'Good morning, Jordan',
      bankingBalance: '$5,620.00',
      bankingCount: 1,
      creditCardBalance: '$8,400',
      monthlyIncome: '$7,400',
      creditScore: 652,
      creditScoreLabel: 'Fair',
      netWorth: '-$2,780',
      spending: '$3,850',
      spendingNote: 'Slightly over budget',
      rewardPoints: '95 pts',
    },
  },
  {
    id: 'persona-david',
    name: 'David',
    avatar: require('@/assets/images/personas/david-kim.png'),
    accentColor: '#8aade0',
    age: 37,
    subtitle: 'Multi-product user, complex portfolio',
    flows: [
      { scenarioId: '', label: 'Free chat', icon: 'message-circle', description: 'Open conversation with Coach' },
      { scenarioId: 'memory-lifecycle', label: 'Memory & privacy controls', icon: 'brain', description: 'Edit, pause, or delete what Coach remembers' },
    ],
    financialProfile: {
      greeting: 'Good morning, David',
      bankingBalance: '$27,282.12',
      bankingCount: 2,
      investBalance: '$145,120.50',
      monthlyIncome: '$11,250',
      creditScore: 782,
      creditScoreLabel: 'Excellent',
      netWorth: '$278,220',
      spending: '$3,600',
      spendingNote: 'Under budget',
      rewardPoints: '520 pts',
    },
  },
];

export const PERSONA_ORDER = ['persona-maya', 'persona-marcus', 'persona-jordan', 'persona-david'];
