import { Persona } from './types';

export const PERSONAS: Persona[] = [
  {
    id: 'persona-maya',
    name: 'Maya',
    avatar: require('@/assets/images/personas/maya-chen.png'),
    accentColor: '#e8b4a2',
    age: 25,
    subtitle: 'New member, no history with Coach',
    flows: [
      { scenarioId: '', label: 'Free chat', icon: 'message-circle', description: 'Open conversation with Coach' },
      { scenarioId: 'cold-start', label: 'First-time onboarding', icon: 'sparkles', description: 'New member meets Coach for the first time' },
      { scenarioId: 'goal-discovery', label: 'Goal creation', icon: 'target', description: 'Coach guides setting up a savings goal' },
      { scenarioId: 'cross-product', label: 'Bonus allocation', icon: 'layers', description: 'Splitting a $3K bonus across goals and products' },
    ],
    financialProfile: {
      greeting: 'Good morning, Maya',
      bankingBalance: '$3,847.52',
      bankingCount: 1,
      creditCardBalance: '$4,200',
      monthlyIncome: '$9,580',
      creditScore: 698,
      creditScoreLabel: 'Fair',
      netWorth: '$1,748',
      spending: '$4,680',
      spendingNote: 'On track this month',
      rewardPoints: '120 pts',
    },
  },
  {
    id: 'persona-marcus',
    name: 'Marcus',
    avatar: require('@/assets/images/personas/marcus-johnson.png'),
    accentColor: '#e5d38a',
    age: 32,
    subtitle: 'Active goals, regular check-ins',
    flows: [
      { scenarioId: '', label: 'Free chat', icon: 'message-circle', description: 'Open conversation with Coach' },
      { scenarioId: 'returning-member', label: 'Personalized check-in', icon: 'user-check', description: 'Coach remembers past context and goals' },
      { scenarioId: 'proactive-risk', label: 'Spending alert', icon: 'alert-triangle', description: 'Coach flags a goal at risk from overspending' },
      { scenarioId: 'cross-product', label: 'Bonus allocation', icon: 'layers', description: 'Splitting a $3K bonus across goals and products' },
    ],
    financialProfile: {
      greeting: 'Good morning, Marcus',
      bankingBalance: '$12,450.00',
      bankingCount: 2,
      investBalance: '$38,200',
      creditCardBalance: '$2,940',
      monthlyIncome: '$12,083',
      creditScore: 742,
      creditScoreLabel: 'Good',
      netWorth: '$89,400',
      spending: '$892',
      spendingNote: '↓8% from last week',
      rewardPoints: '250 pts',
    },
  },
  {
    id: 'persona-sarah',
    name: 'Sarah',
    avatar: require('@/assets/images/personas/sarah-patel.png'),
    accentColor: '#c4a0a8',
    age: 29,
    subtitle: 'Values privacy, manages her data',
    flows: [
      { scenarioId: '', label: 'Free chat', icon: 'message-circle', description: 'Open conversation with Coach' },
      { scenarioId: 'memory-lifecycle', label: 'Memory & privacy controls', icon: 'brain', description: 'Edit, pause, or delete what Coach remembers' },
      { scenarioId: 'milestone-celebration', label: 'Milestone celebration', icon: 'award', description: 'Coach recognizes hitting 75% of a savings goal' },
      { scenarioId: 'returning-member', label: 'Personalized check-in', icon: 'user-check', description: 'Coach remembers past context and goals' },
    ],
    financialProfile: {
      greeting: 'Good morning, Sarah',
      bankingBalance: '$8,920.30',
      bankingCount: 2,
      investBalance: '$45,000',
      monthlyIncome: '$8,750',
      creditScore: 756,
      creditScoreLabel: 'Good',
      netWorth: '$62,320',
      spending: '$3,200',
      spendingNote: 'Under budget',
      rewardPoints: '380 pts',
    },
  },
];

export const PERSONA_ORDER = ['persona-maya', 'persona-marcus', 'persona-sarah'];
