import { Persona } from './types';

export const PERSONAS: Persona[] = [
  {
    id: 'persona-maya',
    name: 'Maya',
    avatar: require('@/assets/images/personas/maya-chen.png'),
    accentColor: '#e8b4a2',
    age: 25,
    subtitle: 'New member, no history with Coach',
    flows: [
      { scenarioId: 'cold-start', label: 'First visit', icon: 'sparkles', description: 'Brand new to Coach — cold-start onboarding' },
      { scenarioId: 'goal-discovery', label: 'Setting a goal', icon: 'target', description: 'Guided goal creation with Coach suggestions' },
      { scenarioId: 'cross-product', label: 'Bonus allocation', icon: 'layers', description: 'Coach helps allocate a bonus across products' },
    ],
    financialProfile: {
      greeting: 'Good morning, Maya',
      bankingBalance: '$3,847.52',
      bankingCount: 1,
      creditCardBalance: '$4,200',
      monthlyIncome: '$9,580',
      creditScore: 698,
      creditScoreLabel: 'Fair',
      netWorth: '$1,748',
      spending: '$4,680',
      spendingNote: 'On track this month',
      rewardPoints: '120 pts',
    },
  },
  {
    id: 'persona-marcus',
    name: 'Marcus',
    avatar: require('@/assets/images/personas/marcus-johnson.png'),
    accentColor: '#e5d38a',
    age: 32,
    subtitle: 'Active goals, regular check-ins',
    flows: [
      { scenarioId: 'returning-member', label: 'Weekly check-in', icon: 'user-check', description: 'Returning member with active goals and history' },
      { scenarioId: 'proactive-risk', label: 'Goal at risk', icon: 'alert-triangle', description: 'Coach flags a savings goal falling behind' },
      { scenarioId: 'cross-product', label: 'Bonus allocation', icon: 'layers', description: 'Coach helps allocate a bonus across products' },
    ],
    financialProfile: {
      greeting: 'Good morning, Marcus',
      bankingBalance: '$12,450.00',
      bankingCount: 2,
      investBalance: '$38,200',
      creditCardBalance: '$2,940',
      monthlyIncome: '$12,083',
      creditScore: 742,
      creditScoreLabel: 'Good',
      netWorth: '$89,400',
      spending: '$892',
      spendingNote: '↓8% from last week',
      rewardPoints: '250 pts',
    },
  },
  {
    id: 'persona-sarah',
    name: 'Sarah',
    avatar: require('@/assets/images/personas/sarah-patel.png'),
    accentColor: '#c4a0a8',
    age: 29,
    subtitle: 'Values privacy, manages her data',
    flows: [
      { scenarioId: 'memory-lifecycle', label: 'Managing preferences', icon: 'brain', description: 'Reviewing and managing Coach memory settings' },
      { scenarioId: 'milestone-celebration', label: 'Milestone reached', icon: 'award', description: 'Coach celebrates a completed savings milestone' },
      { scenarioId: 'returning-member', label: 'Weekly check-in', icon: 'user-check', description: 'Returning member with active goals and history' },
    ],
    financialProfile: {
      greeting: 'Good morning, Sarah',
      bankingBalance: '$8,920.30',
      bankingCount: 2,
      investBalance: '$45,000',
      monthlyIncome: '$8,750',
      creditScore: 756,
      creditScoreLabel: 'Good',
      netWorth: '$62,320',
      spending: '$3,200',
      spendingNote: 'Under budget',
      rewardPoints: '380 pts',
    },
  },
  {
    id: 'persona-jordan',
    name: 'Jordan',
    avatar: require('@/assets/images/personas/jordan-rivera.png'),
    accentColor: '#b5c4a0',
    age: 28,
    subtitle: 'Carries debt, needs a payoff plan',
    flows: [
      { scenarioId: 'goal-discovery', label: 'Tackling debt', icon: 'target', description: 'Building a structured plan to pay down debt' },
      { scenarioId: 'proactive-risk', label: 'Goal at risk', icon: 'alert-triangle', description: 'Coach flags a savings goal falling behind' },
      { scenarioId: 'cold-start', label: 'First visit', icon: 'sparkles', description: 'Brand new to Coach — cold-start onboarding' },
    ],
    financialProfile: {
      greeting: 'Good morning, Jordan',
      bankingBalance: '$5,620.00',
      bankingCount: 1,
      creditCardBalance: '$8,400',
      monthlyIncome: '$7,400',
      creditScore: 652,
      creditScoreLabel: 'Fair',
      netWorth: '-$2,780',
      spending: '$3,850',
      spendingNote: 'Slightly over budget',
      rewardPoints: '95 pts',
    },
  },
  {
    id: 'persona-aisha',
    name: 'Aisha',
    avatar: require('@/assets/images/personas/aisha-williams.png'),
    accentColor: '#d4a636',
    age: 31,
    subtitle: 'Consistent saver, hitting milestones',
    flows: [
      { scenarioId: 'proactive-risk', label: 'Spending alert', icon: 'alert-triangle', description: 'Coach flags unusual spending patterns' },
      { scenarioId: 'returning-member', label: 'Weekly check-in', icon: 'user-check', description: 'Returning member with active goals and history' },
      { scenarioId: 'milestone-celebration', label: 'Milestone reached', icon: 'award', description: 'Coach celebrates a completed savings milestone' },
    ],
    financialProfile: {
      greeting: 'Good morning, Aisha',
      bankingBalance: '$9,100.75',
      bankingCount: 2,
      investBalance: '$22,500',
      creditCardBalance: '$1,260',
      monthlyIncome: '$9,200',
      creditScore: 728,
      creditScoreLabel: 'Good',
      netWorth: '$54,800',
      spending: '$3,420',
      spendingNote: 'Under budget this month',
      rewardPoints: '210 pts',
    },
  },
  {
    id: 'persona-david',
    name: 'David',
    avatar: require('@/assets/images/personas/david-kim.png'),
    accentColor: '#8aade0',
    age: 37,
    subtitle: 'Multi-product user, complex portfolio',
    flows: [
      { scenarioId: 'milestone-celebration', label: 'Milestone reached', icon: 'award', description: 'Coach celebrates a completed savings milestone' },
      { scenarioId: 'cross-product', label: 'Bonus allocation', icon: 'layers', description: 'Coach helps allocate a bonus across products' },
      { scenarioId: 'memory-lifecycle', label: 'Managing preferences', icon: 'brain', description: 'Reviewing and managing Coach memory settings' },
    ],
    financialProfile: {
      greeting: 'Good morning, David',
      bankingBalance: '$27,282.12',
      bankingCount: 2,
      investBalance: '$145,120.50',
      monthlyIncome: '$11,250',
      creditScore: 782,
      creditScoreLabel: 'Excellent',
      netWorth: '$278,220',
      spending: '$3,600',
      spendingNote: 'Under budget',
      rewardPoints: '520 pts',
    },
  },
];

export const PERSONA_ORDER = [
  'persona-maya', 'persona-marcus', 'persona-sarah',
  'persona-jordan', 'persona-aisha', 'persona-david',
];
