// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/memory-mode/BottomSheet.tsx": () => import("../components/mockups/memory-mode/BottomSheet.tsx"),
  "./components/mockups/memory-mode/CurrentWelcome.tsx": () => import("../components/mockups/memory-mode/CurrentWelcome.tsx"),
  "./components/mockups/memory-mode/IncognitoChat.tsx": () => import("../components/mockups/memory-mode/IncognitoChat.tsx"),
  "./components/mockups/memory-mode/PillSelector.tsx": () => import("../components/mockups/memory-mode/PillSelector.tsx"),
  "./components/mockups/memory-mode/ToggleHeader.tsx": () => import("../components/mockups/memory-mode/ToggleHeader.tsx"),
  "./components/mockups/memory-mode/WelcomeEntry.tsx": () => import("../components/mockups/memory-mode/WelcomeEntry.tsx"),
  "./components/mockups/memory-cards/OverflowMenu.tsx": () => import("../components/mockups/memory-cards/OverflowMenu.tsx"),
  "./components/mockups/memory-cards/SwipeActions.tsx": () => import("../components/mockups/memory-cards/SwipeActions.tsx")
};
